### ISSUE TITLE
onFinish and onStart don't fire up after number change 

### ISSUE THREAD

**Issue by watsonPlaceme** [heyman333/react-animated-numbers#11]
@heyman333  After first load, onFinish and onStart fire up as expected, but when I change number value (for example from setNumber) number is animated but onStart and onFinish don't fire up. I need this for changing styles on start and on finish. Would it be possible to add this functionality? I really like this package, animation is awesome and documentation clear. This small improvement would add more flexibility

**Comment by heyman333** [comment]
@watsonPlaceme  I am working on it

**Comment by heyman333** [comment]
@watsonPlaceme I published new version 0.3.1. can u check it?
