### ISSUE TITLE
Unstable view when scaling

### ISSUE THREAD

**Issue by letsG** [heyman333/react-animated-numbers#14]
First of all thank you very much! Your package helped me a lot, and saved several hours! 

Just noticed that scaling the browser view (cmd + "+" / cmd + "-") breaking the layout.

I'm looking for a workaround and share if find one

this problem appears only on chrome and safari (as i tested) but ff looks fine

**Comment by letsG** [comment]
Thank you very much again! I realized that there would not be any fix of that, so I'll stop use this package! Thanks for your work

**Comment by heyman333** [comment]
@letsG hello. thank you for your praise.
I recently released new version of package v0.5.1, which is built with the latest version of react-spring 
Would you like to try a new version?
