### ISSUE TITLE
clientHeight numeric accuracy is not adequate for  ”useNumberHeight“

### ISSUE THREAD

**Issue by 7PLonG** [heyman333/react-animated-numbers#17]
maybe could use getClientRects()

**Comment by heyman333** [comment]
@7PLonG Thanks! I Will try!

**Comment by heyman333** [comment]
I couldn't see any change? 
Is there any reason for your suggestion?

![스크린샷 2021-09-10 오후 6 20 53](https://user-images.githubusercontent.com/22214150/132831714-6a4b5de6-bc12-47b8-a901-3f3fade17c7f.png)

**Comment by 7PLonG** [comment]
screen resolution 1920*1080 & set fontsize use viewport suchas '1.875vw', 
only win10 display scaling "150%", 
hiddenNode's height  rendered to decimals  "27.3333px",then container use clientHeigh take an integer（27px）
finally animation shows misalignment。

 [https://developer.mozilla.org/en-US/docs/Web/API/Element/clientHeight](url)
> This property will round the value to an integer. If you need a fractional value, use element.getBoundingClientRect().

**Comment by heyman333** [comment]
@7PLonG oh thank you! I will fix it asap

**Comment by heyman333** [comment]
@7PLonG Released in v0.6.3! thanks again
