### ISSUE TITLE
Error when unmounting the component while the animation is still in progress

### ISSUE THREAD

**Issue by markolucky7** [heyman333/react-animated-numbers#18]
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

This error occurs if the parent component of the AnimatedNumbers is unmounted while the animation is in progress.

**Comment by heyman333** [comment]
hey @markolucky7 
Really Thank you for your feedback  👍👍👍

I wii fix it asap

**Comment by heyman333** [comment]
@markolucky7 sorry for late reply. 
Can I know which version you are using?
I did a simple test and there is no problem

If you are not using the latest version, try using the latest version.

https://user-images.githubusercontent.com/22214150/139816095-9f4429eb-8c40-4063-aacf-fa1717aa9e7d.mov

**Comment by markolucky7** [comment]
@heyman333 You are right! It works with the version 0.7.0. I was using the version 0.6.1 🙇
