### ISSUE TITLE
음수 표현시 버그

### ISSUE THREAD

**Issue by realrains** [heyman333/react-animated-numbers#2]
https://github.com/heyman333/react-animated-numbers/blob/2e92a6cc63a3b6bf5ce7c31e5e4a261d1966ca05/index.jsx#L26

음수 표현시 0번 인덱스 문자가 NaN 이 되어서 음수 -> 양수 전환시 에러가 발생하는 것 같습니다

**Comment by heyman333** [comment]
아 네 미처 거기까진 생각 못했네요ㅠㅡㅠ
피드백 감사합니다🙏

**Comment by heyman333** [comment]
close in favor of #3

**Comment by alwaysvailw** [comment]
Is it the reason of this error accord?

"Uncaught TypeError: a.interpolation.calc is not a function"
