### ISSUE TITLE
Module not found V0.10.0

### ISSUE THREAD

**Issue by sudhakar-selva** [heyman333/react-animated-numbers#25]
Latest package (v0.10.0) not working bcuz dist folder is not available inside node_modules/react-animated-numbers/

Issue could be related to invalid package published to npm(without building)

> Note: v0.9.0 working problem.

**Comment by sudhakar-selva** [comment]
@heyman333 could be simple fix, pls check

**Comment by heyman333** [comment]
@sudhakar-selva OMG. I published v0.10.1 with dist. THX so much!
