### ISSUE TITLE
can't load numbers when reload page

### ISSUE THREAD

**Issue by GalaxyTea1** [heyman333/react-animated-numbers#26]
First I npm start the app it working but I reload the page it not load numbers?

**Comment by GalaxyTea1** [comment]
I think it's a browser bug, I use Edge and it not working but I use Chrome it working @@. I will close this post. Thanks

**Comment by GalaxyTea1** [comment]
![image](https://user-images.githubusercontent.com/66195006/148882483-dbba2c83-75f3-47b3-a69f-34e09962e50d.png)

**Comment by heyman333** [comment]
@GalaxyTea1 oh. Could you upload image or video for reference?

**Comment by GalaxyTea1** [comment]
![image](https://user-images.githubusercontent.com/66195006/149075351-3c9a8c0f-30e6-46f7-9548-bfc0975d1abb.png)
If I refresh the page, it does not work animation numbers. And now I use react-spring. Thank you a lot.

**Comment by heyman333** [comment]
can you check it with lateset version 0.12.2?
