### ISSUE TITLE
Can't find custom style example page

### ISSUE THREAD

**Issue by arburhan** [heyman333/react-animated-numbers#30]
![image](https://user-images.githubusercontent.com/90565640/169741373-4b22c313-fd98-4e9a-9583-6b5640c9d981.png)

# When  click on 'example' link it show 404 not found page.

![image](https://user-images.githubusercontent.com/90565640/169741415-4ed17868-b736-46ef-bab0-95bf1b0a1a3f.png)

## Please fix it as soon as possible

**Comment by heyman333** [comment]
@arburhan oh. I will update docs ASAP. thanks
