### ISSUE TITLE
Allow other locales for separators than only "en-US" (includeComma)

### ISSUE THREAD

**Issue by mmousawy** [heyman333/react-animated-numbers#36]
Currently the `includeComma` prop is only a boolean that applies `Math.abs(animateToNumber).toLocaleString("en-US")` to the resulting number.

It would be really nice if we could supply our own locale to this method to apply a dot (`.`) as a separator (in the case of `"nl-NL"`).

Suggestion:
```jsx
<AnimatedNumbers
  includeComma="nl-NL"
/>
```

```jsx
const animteTonumberString = typeof includeComma === 'string'
    ? Math.abs(animateToNumber).toLocaleString(includeComma)
    : includeComma
      ? Math.abs(animateToNumber).toLocaleString("en-US")
      : String(Math.abs(animateToNumber));
```

**Comment by heyman333** [comment]
@mmousawy
good suggestion!
It doesn't seem that difficult to fix the code.

How about making `pull request`?
