### ISSUE TITLE
not work on nextjs

### ISSUE THREAD

**Issue by bluelovers** [heyman333/react-animated-numbers#42]
![image](https://user-images.githubusercontent.com/167966/213026789-dd5e8c16-66b7-4974-8640-b8969b2526ac.png)

**Comment by JohnGale87** [comment]
What is the specific issue? Did you see this here:

https://github.com/heyman333/react-animated-numbers/issues/40

**Comment by JohnGale87** [comment]
Also ensure your `configs[].tension` is not Zero.

```
tension: Math.max(1, getYourTension()),
```

**Comment by heyman333** [comment]
@bluelovers please try again as @JohnGale87  said! Thanks :D

**Comment by ezekielharvey** [comment]
> Also ensure your `configs[].tension` is not Zero.
> 
> ```
> tension: Math.max(1, getYourTension()),
> ```

No, this doesn't seem to be the problem
