### ISSUE TITLE
Nextjs - Not Working

### ISSUE THREAD

**Issue by paulaneesh7** [heyman333/react-animated-numbers#52]
Not working with Nextjs v13.5.4 even after following what's been said in the docs
It stays like this:
<img width="98" alt="image" src="https://github.com/heyman333/react-animated-numbers/assets/126695924/b75d7091-d20b-47ca-a4f2-ff078b187272">

**Comment by sahasuvankar7** [comment]
Yeah facing the same issue

**Comment by KINYENJE** [comment]
i'm also facing the same problem

**Comment by holiharshil** [comment]
Not working with Next.js v13.5.6. Anyone give solution . It's working with Next.js v13.4.15

**Comment by heyman333** [comment]
https://github.com/heyman333/react-animated-numbers/issues/51#issuecomment-1742257182 
this might work

**Comment by paulaneesh7** [comment]
I have tried that, it's still not

**Comment by supunsathsara** [comment]
Facing the same issue with next `v14.0.1`
`v13.4.15` worked fine.

**Comment by TouhidZaman** [comment]
Yup, not working in nextjs latest versions

**Comment by heyman333** [comment]
Updated library to use framer-motion. Please check again with v0.17.0
