### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by holiharshil** [heyman333/react-animated-numbers#53]
Not working with Next.js v13.5.6.
Code: 
` <AnimatedNumbers
                  includeComma
                  animateToNumber={parseInt(achievement.value)}
                  locale="en-US"
                  className="text-white text-4xl font-bold"
                  configs={(_, index) => {
                    return {
                      mass: 1,
                      friction: 100,
                      tensions: 140 * (index + 1),
                    };
                  }}
                ></AnimatedNumbers>`

**Comment by Bruton88** [comment]
Nextjs 13.5.4 ,example code ,whatever using dynamic import or not ,the output just show 0,000

**Comment by heyman333** [comment]
https://github.com/heyman333/react-animated-numbers/issues/51#issuecomment-1742257182
this might work

**Comment by stefiHB** [comment]
I have same issue.

![image](https://github.com/heyman333/react-animated-numbers/assets/20320590/db14d45a-7677-4640-8855-b25963e1a82e)

The config callback is working, but the outcome of the animated-numbers doesn't work. 

  "dependencies": {
     ...
    "next": "14.0.1",
    "react-animated-numbers": "^0.16.0",
}

**Comment by TouhidZaman** [comment]
Also not working on my nextjs 13.6 project. previously worked on earlier vertion

**Comment by heyman333** [comment]
Updated library to use framer-motion. Please check again with v0.17.0
