### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by JanMesaric** [heyman333/react-animated-numbers#55]
With minimal implementation as described in README I get the following error:
`TypeError: Cannot read property 'toLowerCase' of undefined, js engine: hermes`

Using "react-native": "0.71.8"

**Comment by heyman333** [comment]
@JanMesaric hello.
this is not for `react-native` 
you can use https://github.com/heyman333/react-native-animated-numbers
